### ISSUE TITLE
Account ownership

### ISSUE THREAD

**Issue by mgastonportillo** [gale/try_git#1]
Hello there,

**I trust this message finds you well**, breaking through the long silence.

I'm reaching out concerning this GitHub account, which has been inactive for the past 12 years. It seems to align perfectly with the branding for my planned open-source organization. Considering its prolonged inactivity, I'm wondering if there's a possibility for ownership transfer.

Can we open a channel of communication to discuss this matter? Your response would be greatly appreciated.

Best regards,
Gastón

**Comment by gale** [comment]
Hello,

Thank you for reaching out. I sincerely appreciate your interest. However, after careful consideration, I have decided not to plan any ownership transfer.

If you’d like to create a similar account for your open-source organization, I recommend considering adding a unique prefix or suffix to the desired account name. This way, you can maintain alignment with your branding while avoiding any conflicts.

Wishing you the best with your open-source endeavors! 😊

Best regards,
gale account owner
